### ISSUE TITLE
Vitalium Synth Unusable

### ISSUE THREAD

**Issue by takuvata** [flathub/org.freedesktop.LinuxAudio.Plugins.DISTRHO-Ports#5] opened 2021-06-09 16:34 UTC
Vitalium plugin from this bundle is unusable. Playing just an 'init' patch raises DSP usage to arround 30-40% on a very powerful machine (tested on few). Enabling any filter or effect sends usage over 100% and results in broken/garbled sound. Same happens in Ardour, lmms (carla) and Bitwig. Plugin seems to work fine once built as a non-flatpak.

**Comment by hfiguiere** [comment] 2021-06-09 17:02
Did you build it from the exact same source version ?

**Comment by takuvata** [comment] 2021-06-09 17:24
Yes, same tarball.

So, to test I actually built rpms using spec from this repo: https://github.com/timlau/spec_files/tree/master/DISTRHO-Ports - seems to use the same release tarball. Then I installed non-flatpak version of Fedora's Ardour, installed resulting rpm and it seems to work fine, DSP usage is around 6% even with filters and effects enabled. Also sound is ok. Flatpak version suffers from all the mentioned issues to the point where it is plain unusable, it seems DSP usage jumps up even when plugin is just loaded and not doing anything. I am testing with LV2 plugin version - VST3 additionally to sound issues also shows distorted UI.

**Comment by hfiguiere** [comment] 2021-06-23 02:46
I get a lot of assertion from the JUCE code, that could explain

**Comment by zsoli69** [comment] 2021-12-24 12:06
I can confirm this issue is still present in the flatpak version of Vitalium. The native version works fine.

**Comment by rayes0** [comment] 2022-04-14 05:21
I think the problem is that the flatpak built-in meson build system doesn't explicitly use the '--buildtype release' flag, which is recommended here: https://github.com/DISTRHO/DISTRHO-Ports#build-and-install

Perhaps try editing the manifest to use the 'simple' build system with the commands suggested in the README?

**Comment by hfiguiere** [comment] 2022-04-16 15:42
Should be fixed with #7

**Closed as completed by hfiguiere** 2022-04-16 15:42 UTC

**Comment by hfiguiere** [comment] 2022-04-16 15:48
I totally overlooked the buildtype. My bad.
